ssim_inference:
  original_path: "./test_70"
  distorted_path: "./test_70/distorted"
  csv_path: "./csv/ssim_scores.csv"

arniqa_test:
  root: "./test_200"
  regressor_dataset: "kadid10k" # or "live", "csiq", "tid2013", "flive", "spaq"
  output_csv: "./csv/quality_scores.csv"

inference:
  model_path: "./combined_mlp_reg.pkl"
  images_path: "./test_200"
  csv_path: "./csv/predictions.csv"
  batch_size: 10
  num_workers: 1

single_image_inference:
  image_path: "path/to/image.jpg"
  model_path: "./combined_mlp_reg.pkl"